services:
  - docker

before_install:
  - docker build -t emerrell/gnarnia-react -f Dockerfile.dev .

script:
  - docker run -e CI=true emerrell/gnarnia-react npm test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "Gnarnia"
  env: "Gnarnia-env"
  bucket_name: "elasticbeanstalk-us-west-1-923547548913"
  bucket_path: "Gnarnia"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

